### ISSUE TITLE
Theme broken

### ISSUE THREAD

**Issue by VictorTennekes** [catppuccin/fleet#11]
Hi there,
I don't think the template in this repository is supported by fleet anymore, judging by the other themes present in the editor the structure is quite different.

Currently the Catppuccin themes do not seem to be rendering at all (very slight difference in syntax coloring).

**Comment by sgoudham** [comment]
Hey :wave: 

I quickly googled for the [Fleet Themes documentation](https://www.jetbrains.com/help/fleet/color-themes.html) and it looks like it still takes in a JSON file? 

Could you share what JSON structure you're seeing in the other themes, and preferably could you link to their source if it is publicly viewable? 

Thanks!

**Comment by VictorTennekes** [comment]
Hey 👋🏻,
it still accepts the theme file in the `themes` directory, when I apply it not much seems to change though.


I've created a gist with the `.json` config for the `Dark Purple` scheme in Fleet:
https://gist.github.com/VictorTennekes/07f47f634ab6f5ff494a4db47494d4e3

**Comment by ceeeeej** [comment]
Seeing the same, screenshot of the Fleet (left) vs. VS Code (right) catppuccin mocha themes if this helps.

<img width="1563" alt="image" src="https://github.com/catppuccin/fleet/assets/2042178/4519a9b6-1c44-42ad-a86b-d696b2c43d3f">

**Comment by sgoudham** [comment]
Thanks for the screenshot! I'm unsure what has changed recently but one could imagine that Fleet has changed its schema.

Unfortunately our maintainer for this port is currently on hiatus and I don't use Fleet personally. I'd really appreciate if someone could take the time and look into the differences between the built-in colour scheme and the colours defined here and figure out what's going wrong!

Does reverting to an older Fleet version help?

**Comment by VictorTennekes** [comment]
I think I can give it a shot to fix it / re-implement it this weekend 😄

**Comment by ceeeeej** [comment]
I poked around for a few minutes, the current version here has a bunch of syntax / variable names that aren't present in the latest themes bundled with the app.

Also didn't find any documentation on it from Jetbrains.

Good luck.

**Comment by sgoudham** [comment]
Sounds like JetBrains alright... it's absolutely miserable finding anything concrete for theming JetBrains IDEs.

I'll try to see if I can redownload Fleet to mess about with it at some point

**Comment by backwardspy** [comment]
opacity is the preferable approach, you can use the [`add`/`sub`/`mod` filters](https://github.com/catppuccin/whiskers#filters) with the `opacity=` keyword argument to apply transparency changes to colours.

if that doesn't work for any reason, another option is to mix colours with base or text to generate shades.

for example this template:

```jinja
{% for i in range(end=10) -%}
Red {{i}} = #{{ base | mix(color=red, amount=i/10) | get(key="hex") }}
{% endfor -%}
```

produces these shades:

![image](https://github.com/catppuccin/fleet/assets/289746/64d22816-7d44-4160-bdd1-2d8e2d563470)

i wouldn't worry too much about going off-palette, the primary aim is for ports to capture catppuccin's look & feel rather than rigidly sticking to the preset colours. shades generated in either of these ways generally meet the criteria!

**Comment by VictorTennekes** [comment]
Cool thanks for the help! I'll try to put some work into it this weekend. As mentioned before the JetBrains docs are "suboptimal" to say the least 😂

**Comment by thelooter** [comment]
> I think I can give it a shot to fix it / re-implement it this weekend 😄

I already started working on it. I might be able to commit some stuff later

**Comment by davfsa** [comment]
Hey!

Only just now ran into this issue, but I also noticed that the new version didn't seem to work with the theme, so I started tweaking it to try and make it work

This is the current state of things on my end:

![image](https://github.com/catppuccin/fleet/assets/29100934/a129653b-dd21-4e4a-ba23-a05dc585fe49)

Trying to get a single theme to function, as it seems like most of the fixes are just renaming existing fields and then odd removal of some no longer existing fields

Also made some improvements to the theme that I hope are welcome!

Still a WIP and someone will most probably finish before me, but wanted to share nonetheless and maybe merge my work with theirs when a PR makes it way to the repo

**Comment by VictorTennekes** [comment]
Nice one! I think once one of the themes is ported It should be relatively easy adapting it to the other using [whiskers](https://www.github.com/catppuccin/whiskers). All the changes are easily converted to the `fleet.tera` file and whiskers can take care of the generation of all the themes.

**Comment by davfsa** [comment]
Yep, noticed that there is a new theme template, which I greatly appreciate. It is making this whole experience 10x nicer to port.

The only reason that I started with the final theme file is that fleet autocomplete has support for its theme file, so it is easy to find the new naming.

*There is probably a JSON spec for it, but I have not been able to find it online and have not gone as far as to look into the jar. I might do that when I am done and will report back what I find. Might help make any further improvements*

**Comment by thelooter** [comment]
> Yep, noticed that there is a new theme template, which I greatly appreciate. It is making this whole experience 10x nicer to port.
> 
> The only reason that I started with the final theme file is that fleet autocomplete has support for its theme file, so it is easy to find the new naming.
> 
> _There is probably a JSON spec for it, but I have not been able to find it online and have not gone as far as to look into the jar. I might do that when I am done and will report back what I find. Might help make any further improvements_

That would probably have made a lot of things easier for me

**Comment by thelooter** [comment]
Created a PR that mostly fixes the issues. Please try and report any findings

**Comment by sgoudham** [comment]
> That would probably have made a lot of things easier for me

Fwiw, whiskers doesn't enforce the file extension of the template. You could rename the template file to gain the autocomplete but I'm unsure how that work with the linting errors from normal JSON.

cc: @backwardspy - I can't remember but can the `read_file()` function work to our advantage here? I can't quite remember the semantics.
