### ISSUE TITLE
Outdated color format in themes

### ISSUE THREAD

**Issue by drukarev** [catppuccin/fleet#39]
Catppuccin themes use an old color format (example: "button.secondary.background.pressed": "ccd0da40%"). This format is deprecated and it will stop working in one of the next Fleet releases. A correct format is described here: https://www.jetbrains.com/help/fleet/modifying-theme-settings.html#supported-color-formats

**Comment by davfsa** [comment]
Thanks for bringing this up!

Will look into updating all the colours to match

**Comment by davfsa** [comment]
This has now been fixed!
