### ISSUE TITLE
The color section of the warning prompt in the upper-left corner has a problem

### ISSUE THREAD

**Issue by diantongren** [catppuccin/fleet#5]
The color section of the warning prompt in the upper-left corner has a problem, like this.

<img width="61" alt="image" src="https://github.com/catppuccin/fleet/assets/77529255/b132344f-63a8-4cf9-a2ff-d878bb6c35c9">
<img width="35" alt="image" src="https://github.com/catppuccin/fleet/assets/77529255/b4bc490a-d147-4acc-b36e-d2fc1ef5bcab">

Only some parts have problem.
<img width="32" alt="image" src="https://github.com/catppuccin/fleet/assets/77529255/c2ef3b57-64c0-4dbf-a7da-5e9b36a7f4d4">

And there is no border after clicking to expand.
<img width="364" alt="image" src="https://github.com/catppuccin/fleet/assets/77529255/23859a1e-944d-4114-abe2-6bba09b72618">

**Comment by kkrypt0nn** [comment]
You mean at the upper right corner, right? For me it looks fine.
![image](https://github.com/catppuccin/fleet/assets/43011723/19f6454b-6fc3-41b9-b7c7-ebbcd75c390d)

![image](https://github.com/catppuccin/fleet/assets/43011723/aeb18d80-1248-423c-90c1-b2371e1dc104)


For the border, I know it's inconvenient but there isn't really something that can be done about (at the moment) as JetBrains has made it that everything is shared everywhere, so changing the border for that will change it everywhere:
![image](https://github.com/catppuccin/fleet/assets/43011723/b0777de1-2534-4b0c-9600-b18d8d220813)

As you can see, almost every border gets put in red.
