### ISSUE TITLE
Difficult to read current line when debugging

### ISSUE THREAD

**Issue by ire4ever1190** [catppuccin/fleet#50]
When debugging and you hit a breakpoint, it can be difficult to read the line

Example using Mocha (Frappe, Latte, and Macchiato also look similar to this)
![image](https://github.com/user-attachments/assets/82eda5f9-79bf-4b55-89c8-528954660422)
What it looks like in default dark theme
![image](https://github.com/user-attachments/assets/698fb18f-e78c-4341-a507-a4369c4e25f5)

**Comment by davfsa** [comment]
Thanks for the report!

Will have a look :)

**Comment by davfsa** [comment]
This now looks like this:

![image](https://github.com/user-attachments/assets/2dc40517-3e89-4a67-939b-59956e318a28)

I will make a new release as soon as possible and you can then update the plugin from inside fleet to get the fix :)

Thanks again for reporting it!

**Comment by ire4ever1190** [comment]
Thanks for the quick turnaround!
